# Logistic Regression

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('Heart.csv')
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [4]:
df=df.drop(columns='Unnamed: 0')
df

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [5]:
df['ChestPain']=df['ChestPain'].astype('category')
df['ChestPain']=df['ChestPain'].cat.codes

df['Thal']=df['Thal'].astype('category')
df['Thal']=df['Thal'].cat.codes

df['AHD']=df['AHD'].astype('category')
df['AHD']=df['AHD'].cat.codes
df

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,3,145,233,1,2,150,0,2.3,3,0.0,0,0
1,67,1,0,160,286,0,2,108,1,1.5,2,3.0,1,1
2,67,1,0,120,229,0,2,129,1,2.6,2,2.0,2,1
3,37,1,1,130,250,0,0,187,0,3.5,3,0.0,1,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,3,110,264,0,0,132,0,1.2,2,0.0,2,1
299,68,1,0,144,193,1,0,141,0,3.4,2,2.0,2,1
300,57,1,0,130,131,0,0,115,1,1.2,2,1.0,2,1
301,57,0,2,130,236,0,2,174,0,0.0,2,1.0,1,1
302,38,1,1,138,175,0,0,173,0,0.0,1,NaN,1,0

In [6]:
df.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           4
Thal         0
AHD          0
dtype: int64

In [7]:
df=df.dropna()
df

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,3,145,233,1,2,150,0,2.3,3,0.0,0,0
1,67,1,0,160,286,0,2,108,1,1.5,2,3.0,1,1
2,67,1,0,120,229,0,2,129,1,2.6,2,2.0,2,1
3,37,1,1,130,250,0,0,187,0,3.5,3,0.0,1,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,57,0,0,140,241,0,0,123,1,0.2,2,0.0,2,1
298,45,1,3,110,264,0,0,132,0,1.2,2,0.0,2,1
299,68,1,0,144,193,1,0,141,0,3.4,2,2.0,2,1
300,57,1,0,130,131,0,0,115,1,1.2,2,1.0,2,1
301,57,0,2,130,236,0,2,174,0,0.0,2,1.0,1,1

In [8]:
x=df.drop(columns='AHD')
x

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal
0,63,1,3,145,233,1,2,150,0,2.3,3,0.0,0
1,67,1,0,160,286,0,2,108,1,1.5,2,3.0,1
2,67,1,0,120,229,0,2,129,1,2.6,2,2.0,2
3,37,1,1,130,250,0,0,187,0,3.5,3,0.0,1
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,57,0,0,140,241,0,0,123,1,0.2,2,0.0,2
298,45,1,3,110,264,0,0,132,0,1.2,2,0.0,2
299,68,1,0,144,193,1,0,141,0,3.4,2,2.0,2
300,57,1,0,130,131,0,0,115,1,1.2,2,1.0,2
301,57,0,2,130,236,0,2,174,0,0.0,2,1.0,1

In [9]:
y=df['AHD']

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [12]:
x_train

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal
14,52,1,1,172,199,1,0,162,0,0.5,1,0.0,2
212,41,1,1,130,214,0,2,168,0,2.0,2,0.0,1
238,49,0,2,134,271,0,0,162,0,0.0,2,0.0,1
44,61,0,0,130,330,0,2,169,0,0.0,1,0.0,1
163,58,0,0,100,248,0,2,122,0,1.0,2,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,45,1,0,142,309,0,2,147,1,0.0,2,3.0,2
257,76,0,1,140,197,0,1,116,0,1.1,2,0.0,1
72,62,1,0,120,267,0,0,99,1,1.8,2,2.0,2
237,46,1,0,120,249,0,2,144,0,0.8,1,0.0,2
37,57,1,0,150,276,0,2,112,1,0.6,2,1.0,0

In [13]:
x_test

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal
174,64,1,0,145,212,0,2,132,0,2.0,2,2.0,0
290,67,1,1,152,212,0,2,150,0,0.8,2,0.0,2
51,65,1,0,120,177,0,0,140,0,0.4,1,0.0,2
146,57,1,0,165,289,1,2,124,0,1.0,2,3.0,2
216,46,0,2,105,204,0,0,172,0,0.0,1,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,51,1,1,100,222,0,0,143,1,1.2,2,0.0,1
248,52,1,0,125,212,0,0,168,0,1.0,1,2.0,2
280,57,1,0,110,335,0,0,143,1,3.0,2,1.0,2
253,51,0,1,120,295,0,2,157,0,0.6,1,0.0,1
19,49,1,2,130,266,0,0,171,0,0.6,1,0.0,1

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
scaler=StandardScaler()

In [17]:
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [18]:
x_train_scaled

array([[-0.24431047,  0.70964577,  0.20631428, ..., -0.97203594,
        -0.69641311,  1.13274336],
       [-1.44190059,  0.70964577,  0.20631428, ...,  0.67963488,
        -0.69641311, -0.49996949],
       [-0.57092596, -1.40915375,  1.25801391, ...,  0.67963488,
        -0.69641311, -0.49996949],
       ...,
       [ 0.84440782,  0.70964577, -0.84538535, ...,  0.67963488,
         1.45988822,  1.13274336],
       [-0.89754144,  0.70964577, -0.84538535, ..., -0.97203594,
        -0.69641311,  1.13274336],
       [ 0.30004868,  0.70964577, -0.84538535, ...,  0.67963488,
         0.38173756, -2.13268234]])

In [19]:
x_test_scaled

array([[ 1.06215148,  0.70964577, -0.84538535, ...,  0.67963488,
         1.45988822, -2.13268234],
       [ 1.38876697,  0.70964577,  0.20631428, ...,  0.67963488,
        -0.69641311,  1.13274336],
       [ 1.17102331,  0.70964577, -0.84538535, ..., -0.97203594,
        -0.69641311,  1.13274336],
       ...,
       [ 0.30004868,  0.70964577, -0.84538535, ...,  0.67963488,
         0.38173756,  1.13274336],
       [-0.3531823 , -1.40915375,  0.20631428, ..., -0.97203594,
        -0.69641311, -0.49996949],
       [-0.57092596,  0.70964577,  1.25801391, ..., -0.97203594,
        -0.69641311, -0.49996949]])

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
model=LogisticRegression()

In [22]:
model.fit(x_train_scaled,y_train)

LogisticRegression()

In [23]:
x_train_scaled[:10]

array([[-0.24431047,  0.70964577,  0.20631428,  2.24948808, -0.86311524,
         2.44267613, -1.01694128,  0.57039594, -0.72494651, -0.49412018,
        -0.97203594, -0.69641311,  1.13274336],
       [-1.44190059,  0.70964577,  0.20631428, -0.12697195, -0.59037395,
        -0.40938706,  0.99766277,  0.83619917, -0.72494651,  0.83100109,
         0.67963488, -0.69641311, -0.49996949],
       [-0.57092596, -1.40915375,  1.25801391,  0.09935758,  0.44604292,
        -0.40938706, -1.01694128,  0.57039594, -0.72494651, -0.93582727,
         0.67963488, -0.69641311, -0.49996949],
       [ 0.73553599, -1.40915375, -0.84538535, -0.12697195,  1.5188253 ,
        -0.40938706,  0.99766277,  0.88049971, -0.72494651, -0.93582727,
        -0.97203594, -0.69641311, -0.49996949],
       [ 0.40892051, -1.40915375, -0.84538535, -1.8244434 ,  0.02783962,
        -0.40938706,  0.99766277, -1.20162563, -0.72494651, -0.05241309,
         0.67963488, -0.69641311, -0.49996949],
       [-1.44190059,  0.70964577,  1.25801391, -0.69279576, -1.62679083,
        -0.40938706, -1.01694128,  1.45640672, -0.72494651, -0.93582727,
        -0.97203594, -0.69641311, -0.49996949],
       [-2.09513156, -1.40915375, -0.84538535,  0.32568711, -1.15403927,
        -0.40938706, -1.01694128,  1.45640672, -0.72494651,  0.30095258,
        -0.97203594, -0.69641311, -0.49996949],
       [-1.1152851 , -1.40915375,  0.20631428, -0.80596053, -0.08125689,
        -0.40938706, -1.01694128, -0.00551107, -0.72494651, -0.67080301,
         0.67963488,  0.38173756, -0.49996949],
       [-1.55077242,  0.70964577,  2.30971355,  0.43885187, -0.86311524,
        -0.40938706, -1.01694128,  1.27920456,  1.37941211,  0.30095258,
        -0.97203594, -0.69641311,  1.13274336],
       [ 0.40892051,  0.70964577, -0.84538535,  1.00467569,  0.42786017,
        -0.40938706,  0.99766277, -1.68893156,  1.37941211, -0.22909593,
        -0.97203594, -0.69641311,  1.13274336]])

In [24]:
y_train[:10]

14     0
212    0
238    0
44     1
163    0
295    0
117    0
260    0
41     0
79     1
Name: AHD, dtype: int8

In [25]:
import numpy as np

In [26]:
y_train=np.array(y_train).reshape(-1,1)
y_train[:10]

array([[0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1]], dtype=int8)

In [27]:
y_pred_train=model.predict(x_train_scaled)
y_pred_train[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int8)

In [28]:
model.score(x_train_scaled,y_train)

0.8516746411483254

In [29]:
x_test_scaled[:5]

array([[ 1.06215148,  0.70964577, -0.84538535,  0.72176378, -0.62673946,
        -0.40938706,  0.99766277, -0.75862024, -0.72494651,  0.83100109,
         0.67963488,  1.45988822, -2.13268234],
       [ 1.38876697,  0.70964577,  0.20631428,  1.11784045, -0.62673946,
        -0.40938706,  0.99766277,  0.03878947, -0.72494651, -0.22909593,
         0.67963488, -0.69641311,  1.13274336],
       [ 1.17102331,  0.70964577, -0.84538535, -0.69279576, -1.26313579,
        -0.40938706, -1.01694128, -0.40421592, -0.72494651, -0.5824616 ,
        -0.97203594, -0.69641311,  1.13274336],
       [ 0.30004868,  0.70964577, -0.84538535,  1.85341141,  0.77333246,
         2.44267613,  0.99766277, -1.11302455, -0.72494651, -0.05241309,
         0.67963488,  2.53803889,  1.13274336],
       [-0.89754144, -1.40915375,  1.25801391, -1.54153149, -0.77220148,
        -0.40938706, -1.01694128,  1.01340133, -0.72494651, -0.93582727,
        -0.97203594, -0.69641311, -0.49996949]])

In [30]:
y_test=np.array(y_test).reshape(-1,1)
y_test[:5]

array([[1],
       [1],
       [0],
       [1],
       [0]], dtype=int8)

In [31]:
y_pred_test=model.predict(x_test_scaled)
y_pred_test[:5]

array([1, 1, 0, 1, 0], dtype=int8)

In [32]:
model.score(x_test_scaled,y_test)

0.8333333333333334