# Dimensionality Reduction: PCA

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Heart.csv")
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [3]:
df['ChestPain']=df['ChestPain'].astype('category')
df['ChestPain']=df['ChestPain'].cat.codes

df['Thal']=df['Thal'].astype('category')
df['Thal']=df['Thal'].cat.codes

df['AHD']=df['AHD'].astype('category')
df['AHD']=df['AHD'].cat.codes
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,3,145,233,1,2,150,0,2.3,3,0.0,0,0
1,2,67,1,0,160,286,0,2,108,1,1.5,2,3.0,1,1
2,3,67,1,0,120,229,0,2,129,1,2.6,2,2.0,2,1
3,4,37,1,1,130,250,0,0,187,0,3.5,3,0.0,1,0
4,5,41,0,2,130,204,0,2,172,0,1.4,1,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,3,110,264,0,0,132,0,1.2,2,0.0,2,1
299,300,68,1,0,144,193,1,0,141,0,3.4,2,2.0,2,1
300,301,57,1,0,130,131,0,0,115,1,1.2,2,1.0,2,1
301,302,57,0,2,130,236,0,2,174,0,0.0,2,1.0,1,1
302,303,38,1,1,138,175,0,0,173,0,0.0,1,NaN,1,0

In [4]:
df.isna().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          0
AHD           0
dtype: int64

In [5]:
df=df.dropna()
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,3,145,233,1,2,150,0,2.3,3,0.0,0,0
1,2,67,1,0,160,286,0,2,108,1,1.5,2,3.0,1,1
2,3,67,1,0,120,229,0,2,129,1,2.6,2,2.0,2,1
3,4,37,1,1,130,250,0,0,187,0,3.5,3,0.0,1,0
4,5,41,0,2,130,204,0,2,172,0,1.4,1,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,298,57,0,0,140,241,0,0,123,1,0.2,2,0.0,2,1
298,299,45,1,3,110,264,0,0,132,0,1.2,2,0.0,2,1
299,300,68,1,0,144,193,1,0,141,0,3.4,2,2.0,2,1
300,301,57,1,0,130,131,0,0,115,1,1.2,2,1.0,2,1
301,302,57,0,2,130,236,0,2,174,0,0.0,2,1.0,1,1

In [6]:
x=df.drop(columns=['Unnamed: 0','AHD'])
x

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal
0,63,1,3,145,233,1,2,150,0,2.3,3,0.0,0
1,67,1,0,160,286,0,2,108,1,1.5,2,3.0,1
2,67,1,0,120,229,0,2,129,1,2.6,2,2.0,2
3,37,1,1,130,250,0,0,187,0,3.5,3,0.0,1
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,57,0,0,140,241,0,0,123,1,0.2,2,0.0,2
298,45,1,3,110,264,0,0,132,0,1.2,2,0.0,2
299,68,1,0,144,193,1,0,141,0,3.4,2,2.0,2
300,57,1,0,130,131,0,0,115,1,1.2,2,1.0,2
301,57,0,2,130,236,0,2,174,0,0.0,2,1.0,1

In [7]:
y=df['AHD']

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler=StandardScaler()

In [20]:
x_scaled=scaler.fit_transform(x)
x_scaled[:5]

array([[ 0.94067407,  0.69296322,  2.24755822,  0.75419084, -0.27206074,
         2.40737503,  1.01012964,  0.02159942, -0.69825654,  1.07427684,
         2.26765706, -0.71830622, -2.1414052 ],
       [ 1.38482969,  0.69296322, -0.87327726,  1.60279745,  0.75055465,
        -0.4153902 ,  1.01012964, -1.8111405 ,  1.4321384 ,  0.38572641,
         0.64557701,  2.48726932, -0.50803746],
       [ 1.38482969,  0.69296322, -0.87327726, -0.6601535 , -0.34923926,
        -0.4153902 ,  1.01012964, -0.89477054,  1.4321384 ,  1.33248325,
         0.64557701,  1.41874414,  1.12533028],
       [-1.94633746,  0.69296322,  0.16700123, -0.09441576,  0.05594797,
        -0.4153902 , -1.00339544,  1.63615602, -0.69825654,  2.10710247,
         2.26765706, -0.71830622, -0.50803746],
       [-1.50218184, -1.44307804,  1.20727972, -0.09441576, -0.831605  ,
        -0.4153902 ,  1.01012964,  0.98160604, -0.69825654,  0.29965761,
        -0.97650304, -0.71830622, -0.50803746]])

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=.30,random_state=1)
len(x_train)

209

In [22]:
len(x_test)

90

In [29]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [30]:
y_pred=model.predict(x_train)
y_pred[:5]

array([0, 0, 0, 0, 0], dtype=int8)

In [31]:
y_train[:5]

14     0
212    0
238    0
44     1
163    0
Name: AHD, dtype: int8

In [32]:
model.score(x_train,y_train)

0.8516746411483254

In [33]:
from sklearn.decomposition import PCA

In [34]:
pca=PCA(n_components=3)
x_pca=pca.fit_transform(x_scaled)
x_pca.shape

(299, 3)

In [27]:
x_pca[:5]

array([[ 0.47954179,  1.92867234,  3.51759754],
       [ 3.57118925,  0.99434508, -0.36107891],
       [ 3.05381803, -0.88971214, -0.22944562],
       [-0.35747998, -1.51168889,  1.39871533],
       [-2.13099263,  0.37310819,  0.16995652]])

In [28]:
x_train_pca,x_test_pca,y_train,y_test=train_test_split(x_pca,y,test_size=0.3,random_state=1)
len(x_train_pca)

209

In [35]:
model=LogisticRegression()
model.fit(x_train_pca,y_train)
model.score(x_train_pca,y_train)

0.8229665071770335

In [39]:
pca=PCA(0.95)
x_pca1=pca.fit_transform(x_scaled)
x_pca1.shape

(299, 12)

In [40]:
x_train_pca1,x_test_pca1,y_train,y_test=train_test_split(x_pca1,y,test_size=0.3,random_state=1)
len(x_train_pca1)

209

In [41]:
model=LogisticRegression()
model.fit(x_train_pca1,y_train)
model.score(x_train_pca1,y_train)

0.8516746411483254