In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
df=pd.read_csv("G:\\iit_d\\agam\\project1\\why are employees leaving.csv")
df

,ID,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Division,salary
0,1,0.38,0.53,2,157,3,0,1,0,sales,low
1,2,0.80,0.86,5,262,6,0,1,0,sales,medium
2,3,0.11,0.88,7,272,4,0,1,0,sales,medium
3,4,0.72,0.87,5,223,5,0,1,0,sales,low
4,5,0.37,0.52,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...,...
14994,14995,0.40,0.57,2,151,3,0,1,0,support,low
14995,14996,0.37,0.48,2,160,3,0,1,0,support,low
14996,14997,0.37,0.53,2,143,3,0,1,0,support,low
14997,14998,0.11,0.96,6,280,4,0,1,0,support,low
14998,14999,0.37,0.52,2,158,3,0,1,0,support,low

In [15]:
df=pd.get_dummies(df,dtype=int)
df[:10]

,ID,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Division_IT,...,Division_hr,Division_management,Division_marketing,Division_product_mng,Division_sales,Division_support,Division_technical,salary_high,salary_low,salary_medium
0,1,0.38,0.53,2,157,3,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
1,2,0.80,0.86,5,262,6,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1
2,3,0.11,0.88,7,272,4,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1
3,4,0.72,0.87,5,223,5,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
4,5,0.37,0.52,2,159,3,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
5,6,0.41,0.50,2,153,3,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
6,7,0.10,0.77,6,247,4,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
7,8,0.92,0.85,5,259,5,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
8,9,0.89,1.00,5,224,5,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
9,10,0.42,0.53,2,142,3,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0

In [16]:
x=df.drop(columns=['ID','left'])
x.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,Division_IT,Division_RandD,Division_accounting,Division_hr,Division_management,Division_marketing,Division_product_mng,Division_sales,Division_support,Division_technical,salary_high,salary_low,salary_medium
0,0.38,0.53,2,157,3,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
1,0.80,0.86,5,262,6,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
2,0.11,0.88,7,272,4,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
3,0.72,0.87,5,223,5,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
4,0.37,0.52,2,159,3,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0

In [17]:
y=df["left"]

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=1)

In [20]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [21]:
model.score(x_test,y_test)

0.977

In [22]:
param_grid={
    "criterion":["gini","entropy"],
    "max_depth":[None,2,4,6,8,10],
    "min_samples_split":[2,5,7,10],
    "min_samples_leaf":[1,2,3,4]
}

In [23]:
from sklearn.model_selection import GridSearchCV
grid_search=GridSearchCV(estimator=model,param_grid=param_grid,cv=5,scoring="accuracy")
grid_search.fit(x,y)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 2, 4, 6, 8, 10],
                         'min_samples_leaf': [1, 2, 3, 4],
                         'min_samples_split': [2, 5, 7, 10]},
             scoring='accuracy')

In [24]:
best_params=grid_search.best_params_
best_params

{'criterion': 'entropy',
 'max_depth': 10,
 'min_samples_leaf': 2,
 'min_samples_split': 2}

In [25]:
best_score=grid_search.best_score_
best_score

0.9791985995331777